---
title: "Creating Baseline and Future Means for all GCM/RCP projections"
author: "Annie Kellner"
date: "7/7/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Initials

```{r Initials, message=FALSE, warning=FALSE}

library(stars)
library(sf)
library(dplyr)
library(ggplot2)
library(viridis)
library(ggthemes)

```

## Load Spatial Data

```{r}

data.dir <- "D:/AK/met"
vic.dir <- "D:/NCAR_AK/vic_hydro"

# Spatial

shp <- st_read('./data/spatial-data/Boundary_shapefiles/wrst_mtns.shp') # Wrangell Mountains
shp <- st_transform(shp, 3338)
plot(st_geometry(shp))


```

```{r Create empty dataframes}

variables <- c("DJF_TmeanF", "MAM_TmeanF", "JJA_TmeanF", "SON_TmeanF", "DJF_TmeanF", "DJF_Precip_in", "MAM_Precip_in", "SON_Precip_in", "Annual_max_SWE", "MAM_SON_SWE", "water_balance")

Baseline_Means <- as.data.frame(matrix(data=NA,nrow=0,ncol=length(variables)+2))
names(Baseline_Means) <- c("GCM", "RCP", variables)

Future_Means <- as.data.frame(matrix(data=NA,nrow=0,ncol=length(variables)+2))
names(Future_Means) <- c("GCM", "RCP", variables)

Deltas <- as.data.frame(matrix(data=NA,nrow=0,ncol=length(variables)+2))
names(Deltas) <- c("GCM", "RCP", variables)


```


## MET

# Baseline

```{r}

GCMs <- list.files(path = 'D:/AK/met/monthly/BCSD')
RCPs <- c("rcp45", "rcp85")

for (G in 1:length(GCMs)){
 gcm = GCMs[1]
 for(R in 1:length(RCPs[R])){
   rcp = RCPs[1]
  path = paste(data.dir, "monthly/BCSD", gcm, rcp, sep = '/')
  file.list = list.files(path = path, pattern = '.nc', full.names = TRUE)
 }

hist_filelist = file.list[1:51]
fut_filelist = file.list[76:106]

source('./Code/Create_stars_objects_for_plots.R') # products: cropped_st_hist; cropped_st_fut

# Seasonal Precip

hist_MAM_pcp <- list()

for(H in 1:length(cropped_st_hist)){
  s = cropped_st_hist[[H]]
  s = select(s, pcp)
  hist_MAM_pcp[[H]] = s[,,,3:5]
}

fut_MAM_pcp <- list()

for(F in 1:length(cropped_st_fut)){
  s = cropped_st_fut[[F]]
  s = select(s, pcp)
  fut_MAM_pcp[[F]] = s[,,,3:5]
}

hist_MAM_pcp_stars <- Reduce(c, hist_MAM_pcp)
hist_MAM_pcp_stars %>% mutate(pcp_in = pcp / 25.4) %>% select(pcp_in) -> hist_MAM_pcp_stars

fut_MAM_pcp_stars <- Reduce(c, fut_MAM_pcp) 
fut_MAM_pcp_stars %>% mutate(pcp_in = pcp / 25.4) %>% select(pcp_in) -> fut_MAM_pcp_stars

sum_hist_pcp <- st_apply(hist_MAM_pcp_stars, c("x", "y"), sum) # find sum
sum_fut_pcp <- st_apply(fut_MAM_pcp_stars, c("x", "y"), sum)

Baseline_Means$GCM = GCMs[G]
Baseline_Means$RCP = RCPs[R]
Baseline_Means$MAM_Precip_in = sum_hist_pcp

Future_Means$GCM = GCMs[G]
Future_Means$RCP = RCP[R]
Future_Means$MAM_Precip_in = sum_fut_pcp

delta <- sum_fut_pcp - sum_hist_pcp

# ggplot - delta

ggplot() + 
  geom_stars(data = delta, alpha = 0.8) + 
  geom_sf(data = shp, aes(), fill = NA) + 
  scale_fill_viridis() + 
  theme_map() +
  theme(legend.position = "bottom") +
  theme(legend.key.width = unit(2, "cm")) 


ggsave(filename = paste('./maps/Deltas/', GCMs[G], RCPs[R], "pcp_hist.png", sep = '_'))




```


