---
title: "Calculate variables"
author: "Amber Runyon"
date: "7/23/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

## Initials

```{r Initials, echo=FALSE, message=FALSE, warning=FALSE}

rm(list = ls())

area <- 'WRST_simple' #wrst_mtns, copper_plateau, coastal_mtns, eastern_coast, WRST_simple

library(stars);library(dplyr);library(ggplot2);library(ggthemes);library(viridis);library(here);library(ggrepel);library(rlang);library(ggbiplot);library(units)

met.dir <- "D:/NCAR_AK/met" 
vic.dir <- "D:/NCAR_AK/vic_hydro"

working.dir <- "C:/Users/achildress/Documents/wrst_temp"

data.dir <- paste(working.dir, "Data", area, sep="/")
  
dir.create(data.dir,showWarnings=FALSE)

historical.period <- as.character(seq(1950,1999,1))
future.period <- as.character(seq(2025,2055,1))
daymet.period <- as.character(seq(1980,2016,1))

GCMs <- c("inmcm4.rcp85","ACCESS1-3.rcp45","CanESM2.rcp85")
CFs <- c("Climate Future 1", "Climate Future 2", "Climate Future 3")
cols <- c("#12045C","#ffcccc","#E10720")

CF_GCM <- data.frame(CF=CFs,GCM=GCMs,CF_col=cols)


```

## Load Spatial Data

```{r Load spatial data}

# Spatial
boundary.dir <- "C:/Users/achildress/DOI/NPS-WRST-Resource Stewardship Strategy - Climate/Climate futures development/Data/Boundary_shapefiles/"
shp <- st_read(paste0(boundary.dir, area, ".shp")) # Wrangell Mountains
shp <- st_transform(shp, 3338)
# plot(st_geometry(shp))


```

## Create empty dataframes that will store climate summaries for each GCM.rcp as loop through data

```{r Create empty dataframes}

monthly.variables <- c("Annual.tmeanF","Annual.precipIn","DJF.tmeanF", "MAM.tmeanF", "JJA.tmeanF", "SON.tmeanF","DJF.tmaxF", "MAM.tmaxF", "JJA.tmaxF", "SON.tmaxF","DJF.tminF", "MAM.tminF", "JJA.tminF", "SON.tminF", "DJF.precipIn", "MAM.precipIn", "JJA.precipIn","SON.precipIn")

# annual.variables <- c("freeze.thaw","GDD","freq.hot.days","days.below32","days.below0","WSF,below0","W.days.over0","precip.over99","max.SWE","MAMSON.SWE","SWE.precip","water.balance","max.runoff","mean.soil.moisture","yday.SWE0","mean.soil.temp")

seasons <- factor(c("DJF","MAM","JJA","SON"),levels=c("DJF","MAM","JJA","SON"))

Baseline_Monthly<-CF_GCM[,1:2]

Future_Monthly <- Baseline_Monthly

Daymet_Monthly <- data.frame(CF = "Historical",GCM = "Daymet")

# Baseline_Annual <- expand.grid(GCMs,historical.period); names(Baseline_Annual) <- c("GCM","Year")
# Baseline_Annual <- merge(Baseline_Annual,CF_GCM[,c("GCM","CF")],by="GCM")

# Future_Annual <- expand.grid(GCMs,future.period); names(Future_Annual) <- c("GCM","Year")
# Future_Annual <- merge(Future_Annual,CF_GCM[,c("GCM","CF")],by="GCM")

# Daymet_Annual <- expand.grid("Daymet",daymet.period); names(Daymet_Annual) <- c("GCM","Year")
# Daymet_Annual$CF <- "Historical"

```

## Met monthly parse and variable creation
Loop through met GCM.rcp and summarize each variable

```{r Create met monthly variables, results=hide, eval=FALSE}
memory.limit(size = 60000)

source(here::here("Code", "Metric-development", "met","met-monthly-stars.R"),echo = FALSE) 
source(here::here("Code", "Metric-development", "met","met-monthly-variables.R"),echo = FALSE)

source(here::here("Code", "Metric-development", "met","Annual.tmeanF.R"),echo = FALSE) 
source(here::here("Code", "Metric-development", "met","Annual.precipIn.R"),echo = FALSE) 

```

## Vic monthly parse and variable creation

```{r Create vic monthly variables, results=hide, eval=FALSE}
memory.limit(size = 60000)

source(here::here("Code", "Metric-development", "vic","vic-monthly-stars.R"),echo = FALSE) 

source(here::here("Code", "Metric-development", "vic","max.SWE.R"),echo = FALSE) 
source(here::here("Code", "Metric-development", "vic","MAMSON.SWE.R"),echo = FALSE) 
source(here::here("Code", "Metric-development", "vic","water.balance.R"),echo = FALSE)
source(here::here("Code", "Metric-development", "vic","SWE.precip.R"),echo = FALSE)


```

## Met daily parse and variable creation

```{r Create daily variables, results=hide, eval=TRUE}
gc()
memory.size()
memory.limit(size = 75000)


source(here::here("Code", "Metric-development", "met","met-daily-stars_by_year.R"),echo = FALSE) 
source(here::here("Code", "Metric-development", "vic","SWE-runoff-Pr99.R"),echo = FALSE)

```

